### PR TITLE
(WIP) Add webhook for validating resources

### PR DESCRIPTION
**Pull request by deepakm-ntnx**
Added defaulting and validating functions
Steps:
<pre>
kubebuilder create webhook --group  infrastructure --version v1beta1 --kind NutanixCluster --defaulting --programmatic-validation 
kubebuilder create webhook --group  infrastructure --version v1beta1 --kind NutanixMachine --defaulting --programmatic-validation 
kubebuilder create webhook --group  infrastructure --version v1beta1 --kind NutanixMachineTemplate --defaulting --programmatic-validation
</pre>

Previous PROJECT file was incomplete and hence it was not allowing to add webhook, with current fixes build passes

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**How Has This Been Tested?**:

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and test output_

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by tuxtof** [comment]
@deepakm-ntnx this approach is becoming clearly deprecated
Not sure it worst time to implement it

we need to switch to CEL validation who is the futur

**Comment by thunderboltsid** [comment]
@tuxtof Is CEL supported on all the versions of Kubernetes CAPX intends to support?

**Comment by deepakm-ntnx** [comment]
> @deepakm-ntnx this approach is becoming clearly deprecated Not sure it worst time to implement it
> 
> we need to switch to CEL validation who is the next way to do And way lighter

@tuxtof we also need to support the same for < 1.25 version of k8s. as cel comes in 1.25 onward. also adding checks like image exists in pc is still not possible thru regular expressions

**Comment by tuxtof** [comment]
@thunderboltsid @deepakm-ntnx 
yes CEL support start only with 1.25 but on the other side 1.24 is end of active support in May 2023

for advanced check like image exists webhook is not the right place to do that, or it will break the IaC approach

**Comment by thunderboltsid** [comment]
Looking back at the Machine API Operator Webhooks we implemented for Openshift, https://github.com/openshift/machine-api-operator/blob/master/pkg/webhooks/machine_webhook.go#L1498-L1577 this holds true. We only validate the values of the resources but stop short of validating their existence in the corresponding Prism cluster.

**Review by thunderboltsid — APPROVED** [review]
testing approval process

**Review by thunderboltsid — APPROVED** [review]
testing another role

**Pull request closed without merging**
