### PR TITLE
Cherry-pick bunch of changes from changes made between v1.2.4 and v1.3.0

### PR DESCRIPTION
**Pull request by thunderboltsid**
This PR was created by checkout out a new branch from `release-v1.2` and rebasing to the last change before v1.3.0 that did not alter the CRD i.e. 4d7827373d50b113d3ab9200597d02017a18f8d2

```
$ git rebase 4d7827373d50b113d3ab9200597d02017a18f8d2
```
One new commit was added in this PR: 955431af6f710dba2db9ba2006dffbb91c1be3d8

**How has this been tested?**
```
$ LABEL_FILTERS=prblocker make test-e2e-calico
CNI="/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/cni/calico/calico.yaml" make test-e2e
make[1]: Entering directory '/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix'
GIT_COMMIT_HASH=`git rev-parse HEAD` && \
KO_DOCKER_REPO=ko.local GOFLAGS="-ldflags=-X=main.gitCommitHash=${GIT_COMMIT_HASH}" /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/ko-v0.11.2 build -B --platform=linux/amd64 -t e2e -L .
2024/04/30 19:50:34 Using base gcr.io/distroless/static:nonroot@sha256:e9ac71e2b8e279a8372741b7a0293afda17650d926900233ec3a7b2b7c22a246 for github.com/nutanix-cloud-native/cluster-api-provider-nutanix
2024/04/30 19:50:35 Building github.com/nutanix-cloud-native/cluster-api-provider-nutanix for linux/amd64
2024/04/30 19:50:38 Loading ko.local/cluster-api-provider-nutanix:8d16e55e05caff48e82b5272510a76c67a29167fa5174778dd5fe35793c5e991
2024/04/30 19:50:40 Loaded ko.local/cluster-api-provider-nutanix:8d16e55e05caff48e82b5272510a76c67a29167fa5174778dd5fe35793c5e991
2024/04/30 19:50:40 Adding tag e2e
2024/04/30 19:50:40 Added tag e2e
ko.local/cluster-api-provider-nutanix:8d16e55e05caff48e82b5272510a76c67a29167fa5174778dd5fe35793c5e991
docker tag ko.local/cluster-api-provider-nutanix:e2e ghcr.io/nutanix-cloud-native/cluster-api-provider-nutanix/controller:e2e
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-secret --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-secret.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-nutanix-cluster --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-nutanix-cluster.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-additional-categories --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-additional-categories.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-nmt --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-nmt.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-project --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-project.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-ccm --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-ccm.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-upgrades --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-upgrades.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-md-remediation --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-md-remediation.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-remediation --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-remediation.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-scale-in --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-scale-in.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-csi --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-csi.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1alpha4/cluster-template --load-restrictor LoadRestrictionsNone > /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/infrastructure-nutanix/v1alpha4/cluster-template.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build templates/base > templates/cluster-template.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build templates/csi > templates/cluster-template-csi.yaml
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/kustomize-v4.5.4 build templates/ccm > templates/cluster-template-ccm.yaml
mkdir -p /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/_artifacts
NUTANIX_LOG_LEVEL=debug /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/hack/tools/bin/ginkgo-v2.1.4 -v \
	--trace \
	--progress \
	--tags=e2e \
	--label-filter="!only-for-validation && prblocker" \
	--skip=""clusterctl-Upgrade"" \
	--focus="""" \
	--nodes=1 \
	--no-color=false \
	--output-dir="/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/_artifacts" \
	--junit-report="junit.e2e_suite.1.xml" \
	--timeout="24h" \
	--always-emit-ginkgo-writer \
	 ./test/e2e -- \
	-e2e.artifacts-folder="/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/_artifacts" \
	-e2e.config="/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/config/nutanix.yaml" \
	-e2e.skip-resource-cleanup=false \
	-e2e.use-existing-cluster=false
Running Suite: capx-e2e - /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e
========================================================================================================================
Random Seed: 1714499447

Will run 1 of 33 specs
------------------------------
[SynchronizedBeforeSuite]
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/e2e_suite_test.go:61
  STEP: Initializing a runtime.Scheme with all the GVK relevant for this test @ 04/30/24 19:50:53.41
  STEP: Loading the e2e test configuration from "/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/config/nutanix.yaml" @ 04/30/24 19:50:53.41
  STEP: Creating a clusterctl local repository into "/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/_artifacts" @ 04/30/24 19:50:53.411
  STEP: Reading the ClusterResourceSet manifest /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/data/cni/calico/calico.yaml @ 04/30/24 19:50:53.411
  STEP: Setting up the bootstrap cluster @ 04/30/24 19:51:05.721
  STEP: Creating the bootstrap cluster @ 04/30/24 19:51:05.721
  INFO: Creating a kind cluster with name "test-4o81vq"
Creating cluster "test-4o81vq" ...
 • Ensuring node image (kindest/node:v1.23.6) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.23.6) 🖼
 • Preparing nodes 📦   ...
 ✓ Preparing nodes 📦
 • Writing configuration 📜  ...
 ✓ Writing configuration 📜
 • Starting control-plane 🕹️  ...
 ✓ Starting control-plane 🕹️
 • Installing CNI 🔌  ...
 ✓ Installing CNI 🔌
 • Installing StorageClass 💾  ...
 ✓ Installing StorageClass 💾
  INFO: The kubeconfig file for the kind cluster is /var/folders/g3/lb827bt96z10xz_m_c2xn93w0000gp/T/e2e-kind1234638514
  INFO: Loading image: "ghcr.io/nutanix-cloud-native/cluster-api-provider-nutanix/controller:e2e"
  INFO: Image ghcr.io/nutanix-cloud-native/cluster-api-provider-nutanix/controller:e2e is present in local container image cache
  INFO: Loading image: "registry.k8s.io/cluster-api/cluster-api-controller:v1.4.1"
  INFO: Image registry.k8s.io/cluster-api/cluster-api-controller:v1.4.1 is present in local container image cache
  INFO: Loading image: "registry.k8s.io/cluster-api/kubeadm-bootstrap-controller:v1.4.1"
  INFO: Image registry.k8s.io/cluster-api/kubeadm-bootstrap-controller:v1.4.1 is present in local container image cache
  INFO: Loading image: "registry.k8s.io/cluster-api/kubeadm-control-plane-controller:v1.4.1"
  INFO: Image registry.k8s.io/cluster-api/kubeadm-control-plane-controller:v1.4.1 is present in local container image cache
  STEP: Initializing the bootstrap cluster @ 04/30/24 19:51:22.425
  INFO: clusterctl init --config /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/_artifacts/repository/clusterctl-config.yaml --kubeconfig /var/folders/g3/lb827bt96z10xz_m_c2xn93w0000gp/T/e2e-kind1234638514 --core cluster-api --bootstrap kubeadm --control-plane kubeadm --infrastructure nutanix
  INFO: Waiting for provider controllers to be running
  STEP: Waiting for deployment capi-kubeadm-bootstrap-system/capi-kubeadm-bootstrap-controller-manager to be available @ 04/30/24 19:52:08.522
  INFO: Creating log watcher for controller capi-kubeadm-bootstrap-system/capi-kubeadm-bootstrap-controller-manager, pod capi-kubeadm-bootstrap-controller-manager-6d4987b5bf-6fhws, container manager
  STEP: Waiting for deployment capi-kubeadm-control-plane-system/capi-kubeadm-control-plane-controller-manager to be available @ 04/30/24 19:52:08.534
  INFO: Creating log watcher for controller capi-kubeadm-control-plane-system/capi-kubeadm-control-plane-controller-manager, pod capi-kubeadm-control-plane-controller-manager-67c7668b94-htcdz, container manager
  STEP: Waiting for deployment capi-system/capi-controller-manager to be available @ 04/30/24 19:52:08.542
  INFO: Creating log watcher for controller capi-system/capi-controller-manager, pod capi-controller-manager-86464d4bfd-s5h2c, container manager
  STEP: Waiting for deployment capx-system/capx-controller-manager to be available @ 04/30/24 19:52:08.554
  INFO: Creating log watcher for controller capx-system/capx-controller-manager, pod capx-controller-manager-66768f84cc-gpjps, container kube-rbac-proxy
  INFO: Creating log watcher for controller capx-system/capx-controller-manager, pod capx-controller-manager-66768f84cc-gpjps, container manager
[SynchronizedBeforeSuite] PASSED [75.532 seconds]
------------------------------
SSSSSSSS
------------------------------
When following the Cluster API quick-start Should create a workload cluster [prblocker, slow, network]
/Users/sid.shukla/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.3.5/e2e/quick_start.go:78
  STEP: Creating a namespace for hosting the "quick-start" test spec @ 04/30/24 19:52:08.941
  INFO: Creating namespace quick-start-66c9u3
  INFO: Creating event watcher for namespace "quick-start-66c9u3"
  STEP: Creating a workload cluster @ 04/30/24 19:52:08.969
  INFO: Creating the workload cluster with name "quick-start-t2wqq5" using the "(default)" template (Kubernetes v1.28.7, 1 control-plane machines, 1 worker machines)
  INFO: Getting the cluster template yaml
  INFO: clusterctl config cluster quick-start-t2wqq5 --infrastructure (default) --kubernetes-version v1.28.7 --control-plane-machine-count 1 --worker-machine-count 1 --flavor (default)
  INFO: Applying the cluster template yaml to the cluster
configmap/user-ca-bundle created
configmap/cni-quick-start-t2wqq5-crs-cni created
secret/quick-start-t2wqq5 created
clusterresourceset.addons.cluster.x-k8s.io/quick-start-t2wqq5-crs-cni created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/quick-start-t2wqq5-kcfg-0 created
cluster.cluster.x-k8s.io/quick-start-t2wqq5 created
machinedeployment.cluster.x-k8s.io/quick-start-t2wqq5-wmd created
machinehealthcheck.cluster.x-k8s.io/quick-start-t2wqq5-mhc created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/quick-start-t2wqq5-kcp created
nutanixcluster.infrastructure.cluster.x-k8s.io/quick-start-t2wqq5 created
nutanixmachinetemplate.infrastructure.cluster.x-k8s.io/quick-start-t2wqq5-mt-0 created

  INFO: Waiting for the cluster infrastructure to be provisioned
  STEP: Waiting for cluster to enter the provisioned phase @ 04/30/24 19:52:10.203
  INFO: Waiting for control plane to be initialized
  INFO: Waiting for the first control plane machine managed by quick-start-66c9u3/quick-start-t2wqq5-kcp to be provisioned
  STEP: Waiting for one control plane node to exist @ 04/30/24 19:52:20.242
  INFO: Waiting for control plane to be ready
  INFO: Waiting for control plane quick-start-66c9u3/quick-start-t2wqq5-kcp to be ready (implies underlying nodes to be ready as well)
  STEP: Waiting for the control plane to be ready @ 04/30/24 19:54:00.381
  STEP: Checking all the control plane machines are in the expected failure domains @ 04/30/24 19:54:00.387
  INFO: Waiting for the machine deployments to be provisioned
  STEP: Waiting for the workload nodes to exist @ 04/30/24 19:54:00.407
  STEP: Checking all the machines controlled by quick-start-t2wqq5-wmd are in the "<None>" failure domain @ 04/30/24 19:54:00.413
  INFO: Waiting for the machine pools to be provisioned
  STEP: PASSED! @ 04/30/24 19:54:00.45
  STEP: Dumping logs from the "quick-start-t2wqq5" workload cluster @ 04/30/24 19:54:00.45
Failed to get logs for Machine quick-start-t2wqq5-kcp-q5rfg, Cluster quick-start-66c9u3/quick-start-t2wqq5: error creating container exec: Error response from daemon: No such container: quick-start-t2wqq5-kcp-q5rfg
Failed to get logs for Machine quick-start-t2wqq5-wmd-64fc4fdbccxwxd4b-z95dn, Cluster quick-start-66c9u3/quick-start-t2wqq5: error creating container exec: Error response from daemon: No such container: quick-start-t2wqq5-wmd-64fc4fdbccxwxd4b-z95dn
  STEP: Dumping all the Cluster API resources in the "quick-start-66c9u3" namespace @ 04/30/24 19:54:00.5
  STEP: Deleting cluster quick-start-66c9u3/quick-start-t2wqq5 @ 04/30/24 19:54:00.615
  STEP: Deleting cluster quick-start-t2wqq5 @ 04/30/24 19:54:00.623
  INFO: Waiting for the Cluster quick-start-66c9u3/quick-start-t2wqq5 to be deleted
  STEP: Waiting for cluster quick-start-t2wqq5 to be deleted @ 04/30/24 19:54:00.628
  STEP: Deleting namespace used for hosting the "quick-start" test spec @ 04/30/24 19:54:40.666
  INFO: Deleting namespace quick-start-66c9u3
• [151.753 seconds]
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[SynchronizedAfterSuite]
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/test/e2e/e2e_suite_test.go:113
  STEP: Dumping logs from the bootstrap cluster @ 04/30/24 19:54:40.694
Failed to get logs for the bootstrap cluster node test-4o81vq-control-plane: exit status 2
  STEP: Tearing down the management cluster @ 04/30/24 19:54:40.863
[SynchronizedAfterSuite] PASSED [1.433 seconds]
------------------------------
[ReportAfterSuite] Autogenerated ReportAfterSuite for --junit-report
autogenerated by Ginkgo
[ReportAfterSuite] PASSED [0.009 seconds]
------------------------------

Ran 1 of 33 Specs in 228.719 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 32 Skipped
You're using deprecated Ginkgo functionality:
=============================================
  --ginkgo.always-emit-ginkgo-writer is deprecated  - use -v instead, or one of Ginkgo's machine-readable report formats to get GinkgoWriter output for passing specs.
  --ginkgo.progress is deprecated .  The functionality provided by --progress was confusing and is no longer needed.  Use --show-node-events instead to see node entry and exit events included in the timeline of failed and verbose specs.  Or you can run with -vv to always see all node events.  Lastly, --poll-progress-after and the PollProgressAfter decorator now provide a better mechanism for debugging specs that tend to get stuck.
  --ginkgo.slow-spec-threshold is deprecated --slow-spec-threshold has been deprecated and will be removed in a future version of Ginkgo.  This feature has proved to be more noisy than useful.  You can use --poll-progress-after, instead, to get more actionable feedback about potentially slow specs and understand where they might be getting stuck.

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=2.6.0

PASS

Ginkgo ran 1 suite in 3m54.165123042s
Test Suite Passed
make[1]: Leaving directory '/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/cluster-api-provider-nutanix'
```

### CODE REVIEW

**Comment by thunderboltsid** [comment]
^ Reg. the build, lint, and test failures. unit tests are passing but the code coverage report upload to codecov is failing due to rate limit errors.

**Review by deepakm-ntnx — COMMENTED** [review]
Too many changes to review. Are we sure we need to get all these changes? cant we just take what is needed to oncall fixes?

**Comment by thunderboltsid** [comment]
> Too many changes to review. Are we sure we need to get all these changes? cant we just take what is needed to oncall fixes?

There is one commit for you to review. The rest is already reviewed and merged into the repo just not in this branch.

**Review by deepakm-ntnx — APPROVED** [review]

**Comment by thunderboltsid** [comment]
Merged in https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/pull/428 to keep history of all the commits

**Pull request merged**
