### PR TITLE
Change Cilium options to make E2E test successfully pass

### PR DESCRIPTION
**Pull request by adiantum**
**What this PR does / why we need it**:
Fix Cilium E2E tests

**How Has This Been Tested?**:
E2E test for K8S 1.25 and 1.26 with Cilium CNI successfully passed

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by tuxtof — APPROVED** [review]
LGTM

**Comment by deepakm-ntnx** [comment]
@adiantum we really need to improve on description with context and how did we decide to add these fixes and why was it failing without these fixes etc so that we can review critically.

**Review by thunderboltsid — APPROVED** [review]

**Pull request merged**
