### PR TITLE
Add a QuickStart e2e with cluster class

### PR DESCRIPTION
**Pull request by deepakm-ntnx**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**How Has This Been Tested?**:
<pre>
git push origin HEAD:quickstart-clusterclass
</pre>
<pre>
When following the Cluster API quick-start with ClusterClass Should create a workload cluster [quickstart2, capx-feature-test]
/Users/deepak.muley/go/src/github.com/kubernetes-sigs/cluster-api/test/e2e/quick_start.go:78
  STEP: Creating a namespace for hosting the "quick-start" test spec @ 01/24/24 15:15:32.709
  INFO: Creating namespace quick-start-mcxuvt
  INFO: Creating event watcher for namespace "quick-start-mcxuvt"
  STEP: Creating a workload cluster @ 01/24/24 15:15:32.76
  INFO: Creating the workload cluster with name "quick-start-q2yn0a" using the "topology" template (Kubernetes v1.27.9, 1 control-plane machines, 1 worker machines)
  INFO: Getting the cluster template yaml
  INFO: clusterctl config cluster quick-start-q2yn0a --infrastructure (default) --kubernetes-version v1.27.9 --control-plane-machine-count 1 --worker-machine-count 1 --flavor topology
  INFO: Applying the cluster template yaml to the cluster
configmap/quick-start-q2yn0a-pc-trusted-ca-bundle created
configmap/nutanix-ccm created
secret/quick-start-q2yn0a created
secret/nutanix-ccm-secret created
clusterresourceset.addons.cluster.x-k8s.io/nutanix-ccm-crs created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/quick-start-q2yn0a-kcfg-0 created
clusterclass.cluster.x-k8s.io/e2e created
kubeadmcontrolplanetemplate.controlplane.cluster.x-k8s.io/e2e-kcpt created
nutanixclustertemplate.infrastructure.cluster.x-k8s.io/e2e-nct created
nutanixmachinetemplate.infrastructure.cluster.x-k8s.io/e2e-cp-nmt created
nutanixmachinetemplate.infrastructure.cluster.x-k8s.io/e2e-md-nmt created
configmap/cni-quick-start-q2yn0a-crs-cni created
clusterresourceset.addons.cluster.x-k8s.io/quick-start-q2yn0a-crs-cni created
cluster.cluster.x-k8s.io/quick-start-q2yn0a created

  INFO: Waiting for the cluster infrastructure to be provisioned
  STEP: Waiting for cluster to enter the provisioned phase @ 01/24/24 15:15:36.261
  INFO: Waiting for control plane to be initialized
  INFO: Waiting for the first control plane machine managed by quick-start-mcxuvt/quick-start-q2yn0a-r9dr6 to be provisioned
  STEP: Waiting for one control plane node to exist @ 01/24/24 15:15:46.349
  INFO: Waiting for control plane to be ready
  INFO: Waiting for control plane quick-start-mcxuvt/quick-start-q2yn0a-r9dr6 to be ready (implies underlying nodes to be ready as well)
  STEP: Waiting for the control plane to be ready @ 01/24/24 15:16:46.437
  STEP: Checking all the control plane machines are in the expected failure domains @ 01/24/24 15:16:46.441
  INFO: Waiting for the machine deployments to be provisioned
  STEP: Waiting for the workload nodes to exist @ 01/24/24 15:16:46.464
  STEP: Checking all the machines controlled by quick-start-q2yn0a-md-0-xdfwp are in the "<None>" failure domain @ 01/24/24 15:17:16.515
  INFO: Waiting for the machine pools to be provisioned
  STEP: PASSED! @ 01/24/24 15:17:16.558
  STEP: Dumping logs from the "quick-start-q2yn0a" workload cluster @ 01/24/24 15:17:16.558
Failed to get logs for Machine quick-start-q2yn0a-md-0-xdfwp-mwlt7-7sr6f, Cluster quick-start-mcxuvt/quick-start-q2yn0a: error creating container exec: Error response from daemon: No such container: quick-start-q2yn0a-md-0-xdfwp-mwlt7-7sr6f
Failed to get logs for Machine quick-start-q2yn0a-r9dr6-pw74q, Cluster quick-start-mcxuvt/quick-start-q2yn0a: error creating container exec: Error response from daemon: No such container: quick-start-q2yn0a-r9dr6-pw74q
  STEP: Dumping all the Cluster API resources in the "quick-start-mcxuvt" namespace @ 01/24/24 15:17:16.722
  STEP: Deleting cluster quick-start-mcxuvt/quick-start-q2yn0a @ 01/24/24 15:17:17.181
  STEP: Deleting cluster quick-start-q2yn0a @ 01/24/24 15:17:17.215
  INFO: Waiting for the Cluster quick-start-mcxuvt/quick-start-q2yn0a to be deleted
  STEP: Waiting for cluster quick-start-q2yn0a to be deleted @ 01/24/24 15:17:17.23
  STEP: Deleting namespace used for hosting the "quick-start" test spec @ 01/24/24 15:17:47.265
  INFO: Deleting namespace quick-start-mcxuvt
• [134.581 seconds]
</pre>

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and test output_

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Review by dkoshkin — APPROVED** [review]
As long as the e2e tests are passing in CI, this LGTM!

**Review by thunderboltsid — APPROVED** [review]

**Pull request merged**
