### PR TITLE
remove klog dependency

### PR DESCRIPTION
**Pull request by yannickstruyf3**
**What this PR does / why we need it**:
Removes klog dependency and adds log levels. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
N/A

**How Has This Been Tested?**:
e2e tests

**Special notes for your reviewer**:
N/A

**Release note**:
-->
```release-note
- Add info and debug log levels
```

### CODE REVIEW

**Review by tuxtof — APPROVED** [review]
LGTM

**Review by thunderboltsid — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
