### PR TITLE
Cherry-pick PR #369 to release-v1.3

### PR DESCRIPTION
**Pull request by thunderboltsid**
### Cherry-Pick Details
- **Original PR Title:** remove CPU/Memory resources settings
- **Original PR URL:** https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/pull/369
- **Commit SHA:** 9a6aa49083ab5d959f3fa2ebd2707b3845d4f0a4
- **Cherry-Pick Reason:** We need to make a v1.3.1 release with the limits removed.

### CODE REVIEW

**Review by tuxtof — APPROVED** [review]
/ok-to-test

**Review by yannickstruyf3 — DISMISSED** [review]

**Comment by thunderboltsid** [comment]
Needed to merge #380 to ensure tests here can run as expected.

**Review by tuxtof — APPROVED** [review]
/lgtm

**Review by yannickstruyf3 — APPROVED** [review]

**Pull request merged**
