### PR TITLE
Cherry-pick PR #4013, #406, and #415 to release-v1.2

### PR DESCRIPTION
**Pull request by thunderboltsid**
### Cherry-Pick Details
- **Original PR Titles:**
    * Ensure fallback config is only read when prismCentral is absent
    * Add a provision for handling image based bootstrap
    * Introduce a nutanix prism client cache
- **Original PR URLs:**
    * https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/pull/403
    * https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/pull/406
    * https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/pull/415
- **Original Commit SHAs:**
    * 92800d980d29db57eea6a01744f5be32a316fc05
    * 25ba78f75169dc4255abe82d50b6b5d079b5ae71
    * fac5b21c89419929d08926241f0cff631fb5e164
- **Cherry-Pick Reason:** Cherry-picking changes that allow us to reasonably cleanly cherry-pick client cache changes

The changes also include changes to build files and dependencies that allow us to get builds working in this release train with the new changes.

### CODE REVIEW

**Comment by thunderboltsid** [comment]
> @thunderboltsid: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> ci/prow/e2e-nutanix-features	[d879fcc](https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/commit/d879fcca5b47f8b35fd547b413920ae30ef5bcb1)	[link](https://prow.ncn-ci.ntnxsherlock.com/view/s3/prow-logs/pr-logs/pull/nutanix-cloud-native_cluster-api-provider-nutanix/430/presubmit-capx-v1.2-nutanix-features-k8s-v1.28/1787916162785349632)	true	`/test e2e-nutanix-features`
> [Full PR test history](https://prow.ncn-ci.ntnxsherlock.com/pr-history?org=nutanix-cloud-native&repo=cluster-api-provider-nutanix&pr=430). [Your PR dashboard](https://prow.ncn-ci.ntnxsherlock.com/pr?query=is:pr+state:open+author:thunderboltsid).

Seems the PE user credentials were rotated

**Review by adiantum — APPROVED** [review]
/lgtm
/approve

**Review by deepakm-ntnx — APPROVED** [review]

**Pull request merged**
