### PR TITLE
Set Nutanix CCM cipher-suites to fix sweet32 CVE

### PR DESCRIPTION
**Pull request by tuxtof**
**What this PR does / why we need it**:

Enforce specific tls-cipher-suite to fix Nutanix CCM SWEET32 CVE

**Release note**:
```release-note
- Fix Nutanix CCM Sweet32 issue
```

### CODE REVIEW

**Review by thunderboltsid — APPROVED** [review]

**Review by deepakm-ntnx — APPROVED** [review]
just for completeness, could you please document where did this list come from? and in future how should one keep it up to date.

**Comment by tuxtof** [comment]
> just for completeness, could you please document where did this list come from? and in future how should one keep it up to date. also how is this tested?

I just align with the settings coming from the other components
who are coming from field best practice . compared with other k8s distro

**Pull request merged**
